### ISSUE TITLE
PVForecast data only 2 days

### ISSUE THREAD

**Issue by MyGitIT** [StefaE/PVForecast#14]
Hi,

since a few days, your program receives forecasts only for the upcoming 2 days. After a discussion with the solcast team they said, we should add the parameter 'hours=168' to the query.

THX

**Comment by MyGitIT** [comment]
I solved this issue quick and dirty with adding ", 'hours': 168" in the payload section of the base.py from PySolcast.

**Comment by StefaE** [comment]
Thx. MyGitIT. 

See [Discussion section](https://github.com/StefaE/PVForecast/discussions/13) - hope I can clean this up shortly.

**Comment by StefaE** [comment]
This issue has been resolved - an update to `pysolcast` is needed to make this work (but compatibility with old version is maintained). 

If you are running Python prior to v3.9 (like me), see [minimal requirements](https://github.com/StefaE/PVForecast#minimal-requirements) on how to install the updated version of [PySolcast](https://github.com/mcaulifn/solcast)
