### ISSUE TITLE
Warnung wenn Daten von solcast geholt werden

### ISSUE THREAD

**Issue by LeonSol** [StefaE/PVForecast#26]
Moin @Matze2 @StefaE 

wenn Daten von solcast abgefragt werden, erscheint ein Warnung, dass ein veralteter Befehl eingesetzt wird, der wohlmöglich in der Zukunft nicht mehr unterstützt wird:

Hier die Ausgabe des Logs: https://i.imgur.com/SMMRBNn.png

Es wäre toll, wenn die Funktion entsprechend angepasst wird.

Vielen Dank und sonnige Grüße

Leon

**Comment by StefaE** [comment]
Thx. for reporting, Leon

Confirming the deprecation warning from Pandas 2.1: _Series.__getitem__ treating keys as positions is deprecated_ on line _solcast.py, 146_

Will get fixed ... :-). Pandas 2.x is getting quite agressive with deprecation warnings, so I want to check what else is broken ... (with possible other forecast providers)

**Comment by StefaE** [comment]
Solved with release Version-2.11.03
