### ISSUE TITLE
two roofs  and different # of modules per string

### ISSUE THREAD

**Issue by astrakid** [StefaE/PVForecast#3]
hi,
is it possible to configure my PVSystem with 2 roofs (one east, one west) and 5 strings (3x11, 2x15 modules)?
couldn't find how to put it into the config file, help is appreciated.

regards,
andre

**Comment by StefaE** [comment]
not yet - but coming; expect approx. 1 week from now

**Comment by astrakid** [comment]
what? really cool. as stated, i am not an programmer, but i try to help where i can and understand lots of basics. started with influx2.py as well. just don't have the overview what has to be changed. maybe we can discuss it elsewhere (slack / telegram, / signal / ...)?

**Comment by StefaE** [comment]
Don't have too many of these toys :-( - you can PM me over at https://www.photovoltaikforum.com/, user **Stefan_E**, then we'll figure something out ... eMail or so

**Comment by StefaE** [comment]
Alpha version of a more flexible influx.py sent to astrakid for testing

**Comment by StefaE** [comment]
Branch merged back into trunk, released as v1.01
