### ISSUE TITLE
Detecting correct pvlib version fails

### ISSUE THREAD

**Issue by christ0phd** [StefaE/PVForecast#33]
I've setup PVForecast as described and I am able to use solcast. Whil eplaying around I tried to activate also VisualCrossing and DWD as providers. Unfortunately I get the errors
`Error: Can't run VisualCrossing - pvlib library installation missing or old version (required: >=0.9.0)`
`Error: Can't run MOSMIX_S - pvlib library installation missing or old version (required: >=0.9.0)`
`Error: Can't run MOSMIX_L - pvlib library installation missing or old version (required: >=0.9.0)`

In fact the requirement of pvlib>=0.10.0 is fullfilled with the most current version 0.11.1. Even installing version 0.9.0 or 0.10.0 does not change the behaviour. So there might be something wrong with the detection of the version number?

**Comment by Matze2** [comment]
Hi, I cannot reproduce it. I have also pvlib 0.11.1 and do not see any errors.
Please execute the following line  in the same python environment that you use for PVForecast:
```
python -c "import pvlib; print(pvlib.__version__)"
```
What does it print?

**Comment by christ0phd** [comment]
Hi, I get the set of error messages indicating a missing hdf5 library. After installing the hdf5 package I've got another list of error messages complaining about missing libhdf5-hl. Next missing lib the is libcblas.so.3. This was a bit of struggle as it seems to be included in package libatlas.
Now I'm getting no more error messages.

Thank you!

**Comment by christ0phd** [comment]
As soon as all unresolved dependencies were installed, it works!
