### ISSUE TITLE
Issues with Light Config installation

### ISSUE THREAD

**Issue by rpsmonkey** [StefaE/PVForecast#8]
Hi, 

first of all, thanks a lot for this tool. Helps me a lot!

I followed the minimal installation process to get only the light version running. Doing this I had 2 issues to get it running:
1. I had to comment out "import sqlite3" in file dbrepository.py on line 1. I guess it is not needed when only running light version with Solcast. 
2. I got an error about the OpenWeatherMap api_key. Since it is not necessary for the light config I also commented out the line about OWM: "  self.storePath     = self.config['OpenWeatherMap'].get('storePath')" on file solecist.py line 39. 

I got it running with these two modification and it seems it is running without further problems. 

Thanks,
Robert

**Comment by StefaE** [comment]
Hi Robert,

thx. - 2/ is fixed now; was indeed a bug. Sorry for that!

As for 1/:

- also the light version supports the [Sqlite storage model](SolCast). But it appears that you are not intending to use that, in which case of course you don't need it.

- that said, SQLite should be part of Python but can be installed, if needed, as described [here](https://stackoverflow.com/questions/19530974/how-can-i-add-the-sqlite3-module-to-python).

Stefan
