### ISSUE TITLE
OWM exception in SolCastLight

### ISSUE THREAD

**Issue by JHCD** [StefaE/PVForecast#9]
Hi,

thanks for that great script.
I only run into one exception with your default solcast_light_config:

```
# python3 SolCastLight.py 
------------------------- Start (solcast_light_config.ini)
Traceback (most recent call last):
  File "/solcast/SolCastLight.py", line 23, in <module>
    mySolCast = SolCast(config)
  File "/solcast/PVForecast/solcast.py", line 39, in __init__
    self.storePath     = self.config['OpenWeatherMap'].get('storePath')
  File "/usr/lib/python3.9/configparser.py", line 960, in __getitem__
    raise KeyError(key)
KeyError: 'OpenWeatherMap'
```

The error is in line 39:
> self.storePath     = self.config['OpenWeatherMap'].get('storePath')

Is that really needed?
I commented out the corresponding line as a test and cannot see any errors

Regards,
Jens

**Comment by StefaE** [comment]
Tagging helps - done! Thx., Jens!
